# fly.toml app configuration file generated for lux-exp-movies on 2025-10-12T14:54:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lux-exp-movies'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 5173
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  concurrency = { type = "requests", soft_limit = 20, hard_limit = 25 }

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
